[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mppsol_session = "B7joeuXqPJSCTfUfMacHaWL6eseoDinV7Jxt52gVdfbi"
mppsol_cpi = "624xoctSeGzq1TAVwZU1xbM9RozAd3xZmjPeFXrAY14j"
test_consumer = "65ndFCiYYM3tznTg5Te1x8ALfVP7SxFEwvvUeANYy3Ex"

[programs.devnet]
mppsol_session = "B7joeuXqPJSCTfUfMacHaWL6eseoDinV7Jxt52gVdfbi"
mppsol_cpi = "624xoctSeGzq1TAVwZU1xbM9RozAd3xZmjPeFXrAY14j"
test_consumer = "65ndFCiYYM3tznTg5Te1x8ALfVP7SxFEwvvUeANYy3Ex"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
